--2
DECLARE
     CURSOR C_CLIENTES IS SELECT NUMRUN FROM CLIENTE ;
     V_ARCHIVO BFILE;
     V_IMAGEN BLOB;
     V_RUT_CLIENTE VARCHAR2(100);
     MENSAJE VARCHAR2(100);
 BEGIN
 
    FOR CLI IN C_CLIENTES LOOP
    
          V_RUT_CLIENTE := CLI.NUMRUN||'.JPG';
    

          V_ARCHIVO := BFILENAME('IMG', V_RUT_CLIENTE);
           UPDATE CLIENTE 
           SET FOTO = EMPTY_BLOB()
           WHERE NUMRUN = CLI.NUMRUN
           RETURNING FOTO INTO V_IMAGEN;
            
        DBMS_OUTPUT.PUT_LINE(V_RUT_CLIENTE);
            
        DBMS_LOB.FILEOPEN(V_ARCHIVO, DBMS_LOB.LOB_READONLY);
        DBMS_LOB.LOADFROMFILE(V_IMAGEN, V_ARCHIVO, DBMS_LOB.GETLENGTH(V_ARCHIVO));
        DBMS_LOB.FILECLOSE(V_ARCHIVO);
        COMMIT;
        
    END LOOP;
                                 

 EXCEPTION
 WHEN OTHERS THEN   
     MENSAJE := SQLERRM;
     DBMS_OUTPUT.PUT_LINE(MENSAJE);
     DBMS_LOB.FILECLOSE(V_ARCHIVO);
     
 END;
 /
 
 
