/* Creando funciones con return */
SET SERVEROUTPUT ON;

  CREATE OR REPLACE FUNCTION 
    SALUDO(NOMBRE IN VARCHAR2) RETURN VARCHAR2 IS
  BEGIN
    RETURN 'Hola ' || NOMBRE;
  END SALUDO;
  /

  DECLARE
    MENSAJE VARCHAR2(50) := SALUDO('MATIAS');
  BEGIN 
    DBMS_OUTPUT.PUT_LINE(MENSAJE);
  END;
